apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: evercare
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager-service:9093

    rule_files:
      - "/etc/prometheus/rules/*"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:8096']
        metrics_path: '/EverCare/actuator/prometheus'
        relabel_configs:
          - replacement: 'user-service'
            target_label: application

      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway-service:8089']
        metrics_path: '/EverCare/actuator/prometheus'
        relabel_configs:
          - replacement: 'api-gateway'
            target_label: application

      - job_name: 'eureka'
        static_configs:
          - targets: ['eureka-service:8761']
        metrics_path: '/EverCare/actuator/prometheus'
        relabel_configs:
          - replacement: 'eureka'
            target_label: application

      - job_name: 'keycloak'
        static_configs:
          - targets: ['keycloak-service:8080']
        metrics_path: '/auth/realms/EverCareRealm/protocol/prometheus'
        relabel_configs:
          - replacement: 'keycloak'
            target_label: application

      - job_name: 'evercare-ai'
        static_configs:
          - targets: ['evercare-ai-service:8000']
        metrics_path: '/EverCare/actuator/prometheus'
        relabel_configs:
          - replacement: 'evercare-ai'
            target_label: application

      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend-service:80']
        metrics_path: '/EverCare/actuator/prometheus'
        relabel_configs:
          - replacement: 'frontend'
            target_label: application

      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:8097']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'notification-service'
            target_label: application

      - job_name: 'medical-record-service'
        static_configs:
          - targets: ['medical-record-service:8092']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'medical-record-service'
            target_label: application

      - job_name: 'communication-service'
        static_configs:
          - targets: ['communication-service:8093']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'communication-service'
            target_label: application

      - job_name: 'cognitive-stimulation-service'
        static_configs:
          - targets: ['cognitive-stimulation-service:8094']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'cognitive-stimulation-service'
            target_label: application

      - job_name: 'blog-service'
        static_configs:
          - targets: ['blog-service:8095']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'blog-service'
            target_label: application

      - job_name: 'appointment-service'
        static_configs:
          - targets: ['appointment-service:8091']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'appointment-service'
            target_label: application

      - job_name: 'tracking-service'
        static_configs:
          - targets: ['tracking-service:8098']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'tracking-service'
            target_label: application

      - job_name: 'dailyme-service'
        static_configs:
          - targets: ['dailyme-service:8099']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'dailyme-service'
            target_label: application

      - job_name: 'alerts-service'
        static_configs:
          - targets: ['alerts-service:8101']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'alerts-service'
            target_label: application

      - job_name: 'activities-service'
        static_configs:
          - targets: ['activities-service:8102']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'activities-service'
            target_label: application

      - job_name: 'ai-service'
        static_configs:
          - targets: ['ai-service:8000']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'ai-service'
            target_label: application

      - job_name: 'face-service'
        static_configs:
          - targets: ['face-service:8100']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'face-service'
            target_label: application

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:9100'
            target_label: __address__

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?:(\d+)
            replacement: $1:$2
            target_label: __address__