apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: evercare
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager-service:9093

    rule_files:
      - "/etc/prometheus/rules/*"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service-deployment:8096']
        metrics_path: '/EverCare/actuator/prometheus'
        relabel_configs:
          - replacement: 'user-service'
            target_label: application

      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway-deployment:8080']
        metrics_path: '/EverCare/actuator/prometheus'
        relabel_configs:
          - replacement: 'api-gateway'
            target_label: application

      - job_name: 'eureka'
        static_configs:
          - targets: ['eureka-deployment:8761']
        metrics_path: '/EverCare/actuator/prometheus'
        relabel_configs:
          - replacement: 'eureka'
            target_label: application

      - job_name: 'keycloak'
        static_configs:
          - targets: ['keycloak-deployment:8080']
        metrics_path: '/auth/realms/EverCareRealm/protocol/prometheus'
        relabel_configs:
          - replacement: 'keycloak'
            target_label: application

      - job_name: 'evercare-ai'
        static_configs:
          - targets: ['evercare-ai-deployment:8100']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'evercare-ai'
            target_label: application

      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend-deployment:80']
        metrics_path: '/actuator/prometheus'
        relabel_configs:
          - replacement: 'frontend'
            target_label: application

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:9100'
            target_label: __address__

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?:(\d+)
            replacement: $1:$2
            target_label: __address__