spring.application.name=communication-service
server.port=8094

# Base de donn�es (m�me base que le user-service)
spring.datasource.url=jdbc:mysql://localhost:3306/EverCaredb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Keycloak JWT validation (jwk-set-uri)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/EverCareRealm/protocol/openid-connect/certs