spring.application.name=communication-service
server.port=8094

# Base de donnes (mme base que le user-service)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/EverCaredb?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-service:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Keycloak JWT validation (jwk-set-uri)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak-service:8080/realms/EverCareRealm/protocol/openid-connect/certs}