pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'badrftw/evercare-medical-record'
        DOCKER_REGISTRY = 'docker.io'
        SONAR_HOST_URL = 'http://10.0.2.15:9000'
        APP_DIR = 'backend/medical-record-service'
        BRANCH_NAME = 'Badr-branch'
    }

    stages {
        stage('Checkout Git') {
            steps {
                git branch: env.BRANCH_NAME,
                        url: 'https://github.com/eyadabbaghi/Esprit-PI-4SAE2-2025-EverCare.git',
                        credentialsId: 'github-evercare'
            }
        }

        stage('Build Maven') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn clean compile -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir(env.APP_DIR) {
                    withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                        sh '''
                            mvn sonar:sonar \
                                -Dsonar.host.url=${SONAR_HOST_URL} \
                                -Dsonar.login=${SONAR_TOKEN} \
                                -Dsonar.projectKey=evercare-medical-record \
                                -Dsonar.projectName="EverCare - Medical Record Service" \
                                -Dsonar.java.binaries=target/classes \
                                -Dsonar.sources=src/main/java \
                                -Dsonar.tests=src/test/java \
                                -Dsonar.modules=
                        '''
                    }
                }
            }
        }

        stage('Package JAR') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        sh "docker build -t ${DOCKER_IMAGE}:${env.BUILD_ID} -f Dockerfile ."
                        sh "docker tag ${DOCKER_IMAGE}:${env.BUILD_ID} ${DOCKER_IMAGE}:latest"
                    }
                }
            }
        }

        stage('Docker Login') {
            steps {
                script {
                    withCredentials([usernamePassword(
                            credentialsId: 'dockerhub-evercare',
                            usernameVariable: 'DOCKER_USER',
                            passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh """
                            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
                        """
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh """
                        docker push ${DOCKER_IMAGE}:${env.BUILD_ID}
                        docker push ${DOCKER_IMAGE}:latest
                    """
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                dir(env.APP_DIR) {
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }

    post {
        always {
            sh 'docker system prune -f || true'
        }
        success {
            echo 'Build and SonarQube analysis successful!'
            mail to: 'Bader.Klila@esprit.tn,baderklila@gmail.com,tnjoker99@gmail.com, jebabli.achref@esprit.tn',
                subject: "[EverCare] Medical Record #${env.BUILD_ID} - SUCCESS",
                body: """BUILD SUCCESSFUL - Medical Record Service

Build Number: ${env.BUILD_ID}
Branch: ${env.BRANCH_NAME}

Docker Image:
- Tag: ${DOCKER_IMAGE}:${env.BUILD_ID}
- Latest: ${DOCKER_IMAGE}:latest

SonarQube: ${SONAR_HOST_URL}/dashboard?id=evercare-medical-record"""
        }
        failure {
            echo 'Pipeline failed!'
            mail to: 'Bader.Klila@esprit.tn,baderklila@gmail.com,tnjoker99@gmail.com',
                subject: "[EverCare] Medical Record #${env.BUILD_ID} - FAILED",
                body: """BUILD FAILED - Medical Record Service

Build: ${env.BUILD_ID}
Branch: ${env.BRANCH_NAME}

Check Jenkins logs for error details."""
        }
    }
}