apiVersion: v1
kind: ConfigMap
metadata:
  name: evercare-config
  namespace: evercare
data:
  DATABASE_HOST: "mysql-service"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "EverCaredb"
  EUREKA_HOST: "eureka-service"
  EUREKA_PORT: "8761"
  KEYCLOAK_URL: "http://keycloak-service:8080"
  KEYCLOAK_REALM: "EverCareRealm"
  GATEWAY_PORT: "8089"
  PROMETHEUS_URL: "http://prometheus-service:9090"