apiVersion: v1
kind: Secret
metadata:
  name: evercare-secrets
  namespace: evercare
type: Opaque
stringData:
  # Database
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: ""
  
  # Keycloak
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  
  # JWT
  JWT_SECRET: "evercare-jwt-secret-key-change-in-production"
  
  # Docker Hub
  DOCKER_USERNAME: "badrftw"
  DOCKER_PASSWORD: ""

  # AI Service
  GROQ_API_KEY: ""