pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'badrftw/evercare-appointment'
        DOCKER_TAG = 'latest'
        APP_DIR = 'backend/appointment-service'
        BRANCH_NAME = 'Badr-branch'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: env.BRANCH_NAME,
                    url: 'https://github.com/eyadabbaghi/Esprit-PI-4SAE2-2025-EverCare.git',
                    credentialsId: 'github-evercare'
            }
        }

        stage('Build') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn clean compile -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir(env.APP_DIR) {
                    withSonarQubeEnv('sonarqube-evercare') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir(env.APP_DIR) {
                    script {
                        sh 'docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f Dockerfile .'
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub-evercare') {
                        docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}").push()
                    }
                }
            }
        }
    }

    post {
        success {
            echo '✅ Build success!'
        }
        failure {
            echo '❌ Build failed!'
        }
    }
}