sonar.projectKey=evercare-appointment
sonar.projectName=EverCare - Appointment Service
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.java.binaries=target/classes

sonar.host.url=http://10.0.2.15:9000
sonar.login=sq_votre_token_ici