spring.application.name=Eureka-service
server.port=8761
eureka.client.register-with-eureka=false
<<<<<<< HEAD
eureka.client.fetch-registry=false
=======
>>>>>>> origin/blog-service-integration+islem
eureka.client.allow-redirects=false
