spring.application.name=cognitive-stimulation-service
server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/alzheimer_cognitive_stimulation?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-service:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.medical-record-service.base-url=${MEDICAL_RECORD_SERVICE_URL:http://medical-record-service:8083}
app.cors.allowed-origins=*

# Actuator
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
