apiVersion: v1
kind: Service
metadata:
  name: communication-service
  namespace: evercare
  labels:
    app: communication-service
spec:
  type: ClusterIP
  ports:
    - port: 8094
      targetPort: 8094
      protocol: TCP
  selector:
    app: communication-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service-deployment
  namespace: evercare
  labels:
    app: communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
        - name: communication-service
          image: badrftw/evercare-communication-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8094
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/EverCaredb?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak-service:8080/realms/EverCareRealm/protocol/openid-connect/certs"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8094
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8094
            initialDelaySeconds: 120
            periodSeconds: 5