apiVersion: v1
kind: Service
metadata:
  name: evercare-ai-frontend
  namespace: evercare
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: evercare-ai-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evercare-ai-frontend-deployment
  namespace: evercare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evercare-ai-frontend
  template:
    metadata:
      labels:
        app: evercare-ai-frontend
    spec:
      containers:
        - name: evercare-ai-frontend
          image: badrftw/evercare-ai-frontend:latest
          ports:
            - containerPort: 8000
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: evercare-secrets
                  key: groq-api-key
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10