package everCare.appointments.dtos;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MedicamentRequestDTO {

    // ========== REQUIRED FIELDS ==========

    private String nomCommercial;                       // e.g. "Donépézil Sandoz"
    private String denominationCommuneInternationale;   // e.g. "Donépézil" (INN/DCI)

    // ========== OPTIONAL FIELDS ==========

    private String dosage;                  // e.g. "10mg"
    private String forme;                   // e.g. "Comprimé", "Patch", "Solution buvable"
    private String codeCIP;                 // 13-digit identifier
    private String laboratoire;             // Manufacturer lab name
    private String indications;             // Therapeutic indications
    private String contreIndications;       // Contraindications
    private String effetsSecondaires;       // Side effects

    // ========== ALZHEIMER-SPECIFIC ==========

    private String photoUrl;                // URL of medication photo
    private String noticeSimplifiee;        // Simplified notice for Alzheimer patients

    // NOTE: Fields NOT included here (set only by server):
    //   - medicamentId  → generated by server (@PrePersist)
    //   - actif         → defaulted to true on creation
    //   - createdAt     → set by server
    //   - updatedAt     → set by server
}