package everCare.appointments.dtos;

import lombok.*;
import java.time.LocalDate;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PrescriptionRequestDTO {

    // ========== REQUIRED LINKS (IDs only, not full objects) ==========

    private String patientId;       // FK → User
    private String doctorId;        // FK → User
    private String medicamentId;    // FK → Medicament

    // ========== OPTIONAL LINK ==========

    private String appointmentId;   // FK → Appointment (null if prescribed outside consultation)

    // ========== DATES ==========

    private LocalDate dateDebut;    // Treatment start date
    private LocalDate dateFin;      // Treatment end date

    // ========== DOSAGE ==========

    private String posologie;       // e.g. "1 comprimé matin et soir"
    private String instructions;    // e.g. "À prendre au cours du repas"

    // ========== RENEWAL ==========

    private Boolean renouvelable;
    private Integer nombreRenouvellements;

    // ========== ALZHEIMER SCHEDULE ==========

    private String priseMatin;      // e.g. "Donépézil 10mg"
    private String priseMidi;
    private String priseSoir;

    private String resumeSimple;    // e.g. "💊 bleu = matin"

    // ========== DOCTOR NOTES ==========

    private String notesMedecin;

    // NOTE: Fields NOT included here (set only by server):
    //   - prescriptionId    → generated by server
    //   - datePrescription  → always LocalDate.now() on creation
    //   - statut            → always "ACTIVE" on creation
    //   - pdfUrl            → generated on demand
    //   - createdAt         → set by server
    //   - updatedAt         → set by server
}