spring.application.name=ApiGateway
server.port=8089

# ================= EUREKA =================
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ================= GATEWAY =================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ================= ROUTES =================

# DAILYME
spring.cloud.gateway.routes[0].id=dailyme
spring.cloud.gateway.routes[0].uri=http://localhost:8098
spring.cloud.gateway.routes[0].predicates[0]=Path=/dailyme/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# TRACKING
spring.cloud.gateway.routes[1].id=tracking
spring.cloud.gateway.routes[1].uri=http://localhost:8099
spring.cloud.gateway.routes[1].predicates[0]=Path=/tracking/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# USER
spring.cloud.gateway.routes[2].id=user
spring.cloud.gateway.routes[2].uri=http://localhost:8096
spring.cloud.gateway.routes[2].predicates[0]=Path=/EverCare/**

# ================= CORS =================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*