spring.application.name=DAILYME-SERVICE

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/evercaredb?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8098

# ? REMOVE THIS LINE (IMPORTANT)
# server.servlet.context-path=/dailyme

# Eureka
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-service:8761/eureka/}

# Debug
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always