spring.application.name=User-service

# MySQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/EverCaredb?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jmx.enabled=false

# Server
server.port=8096
server.servlet.context-path=/EverCare

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-service:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Google Client ID
google.client-id=122324853691-34s6l0e9bho0a65vlj82pf6o63u6b8vg.apps.googleusercontent.com

# Keycloak OIDC
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak-service:8080/realms/EverCareRealm/protocol/openid-connect/certs}

# Keycloak
keycloak.auth-server-url=${KEYCLOAK_SERVER_URL:http://keycloak-service:8080}
keycloak.realm=EverCareRealm
keycloak.client-id=evercare
keycloak.client-secret=WJlavhogez8L7kHutRRg5pgME94736o7

keycloak.face-client-id=face-login-service
keycloak.face-client-secret=BKUipjbBWxlUAPw4a3rM19kGw41OEMsm

# Face service
face.service.url=${FACE_SERVICE_URL:http://face-service:8100}

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always